### ISSUE TITLE
Port to Docker Volume Plugin?

### ISSUE THREAD

**Issue by JimPatterson** [IBM/flocker-driver#5]
Given that flocker's parent company is [shutting down](https://clusterhq.com/2016/12/22/clusterf-ed/), has there been any though of porting this to a [Docker Volume Plugin](https://docs.docker.com/engine/extend/plugins_volume/)?

In my case, I have several applications running in Docker containers with my storage being an IBM Storwise V7000 and I would like to start moving to Docker Swarm so the ability to move the data volumes would be great, but I don't see any options beyond this driver that uses a volume management framework with a questionable future.

**Comment by shay-berman** [comment]
Hello Jim,

Currently, we are working on the native Docker volume plugin solution as well.
For more information, you can contact me directly at bshay@il.ibm.com.

Thanks
Shay Berman
